spring.application.name=sentinel-social
server.port=8080

# Allow large ZIP uploads
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.max-http-form-post-size=500MB
server.tomcat.max-swallow-size=500MB

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
